# Generated by Django 5.2.4 on 2025-07-23 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RADIOLOGIST", "Radiologist"),
                            ("RESEARCHER", "Researcher"),
                            ("STUDENT", "Student"),
                            ("TECHNICIAN", "Technician"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("onboarding_complete", models.BooleanField(default=False)),
                ("dummy", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bucket_name", models.CharField(max_length=255)),
                ("aws_role_arn", models.CharField(max_length=512)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_prefix",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "destination_prefix",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("ocr_requested", models.BooleanField(default=False)),
                ("tag_removal_requested", models.BooleanField(default=False)),
                ("ai_inference_requested", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED_RETRYABLE", "Failed (Retryable)"),
                            ("FAILED_PERMANENT", "Failed (Permanent)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "s3_cleaned_result_key",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "s3_audit_log_key",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("files_processed", models.IntegerField(default=0)),
                ("total_files", models.IntegerField(default=0)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="api.connection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="api_job_user_id_ce81f4_idx"
                    ),
                    models.Index(
                        fields=["connection"], name="api_job_connect_5be6b2_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="api_job_created_f81cf5_idx"
                    ),
                ],
            },
        ),
    ]
