# Generated by Django 5.2.4 on 2025-07-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="cognito_sub",
            new_name="cognito_sub_user_id",
        ),
    ]
