# Generated by Django 5.2.4 on 2025-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_cognito_sub_user_cognito_sub_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="cognito_sub_user_id",
            new_name="user_id",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("RADIOLOGIST", "Radiologist"),
                    ("RESEARCHER", "Researcher"),
                    ("STUDENT", "Student"),
                    ("TECHNICIAN", "Technician"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
