# Generated by Django 5.2.4 on 2025-07-08 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_cognito_sub_user_id_user_user_id_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bucket_name", models.CharField(max_length=255)),
                ("aws_role_arn", models.CharField(max_length=512)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="job",
            name="s3_raw_upload_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="type",
            field=models.CharField(
                choices=[("PURCHASE", "Purchase"), ("USAGE", "Usage")],
                default="USAGE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="destination_artifact_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="files_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="source_artifact_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="total_files",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED_RETRYABLE", "Failed (Retryable)"),
                    ("FAILED_PERMANENT", "Failed (Permanent)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                max_length=128, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["user", "created_at"], name="api_creditt_user_id_2ef63b_idx"
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="api.connection",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["user", "status"], name="api_job_user_id_ce81f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["connection"], name="api_job_connect_5be6b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["created_at"], name="api_job_created_f81cf5_idx"
            ),
        ),
    ]
