# Generated by Django 5.2.4 on 2025-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_connection_alter_job_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="credits_charged",
        ),
        migrations.RemoveField(
            model_name="job",
            name="destination_artifact_id",
        ),
        migrations.RemoveField(
            model_name="job",
            name="ocr_requested",
        ),
        migrations.RemoveField(
            model_name="job",
            name="source_artifact_id",
        ),
        migrations.RemoveField(
            model_name="job",
            name="tag_removal_requested",
        ),
        migrations.RemoveField(
            model_name="user",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="user",
            name="onboarding_complete",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_customer_id",
        ),
        migrations.AddField(
            model_name="job",
            name="destination_prefix",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="source_prefix",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name="CreditTransaction",
        ),
    ]
