# Generated by Django 5.2.4 on 2025-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_job_credits_charged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
    ]
