name: Deploy Medical AI Application

on:
  push:
    branches: [main]

# Add permissions for OIDC token
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_BACKEND: medical-ai-backend-repo
  ECR_REPOSITORY_FRONTEND: medical-ai-frontend-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug OIDC Token
      run: |
        echo "=== GitHub Context ==="
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        echo ""
        echo "=== OIDC Token Request ==="
        if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
          echo "Token request endpoint available: $ACTIONS_ID_TOKEN_REQUEST_URL"
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | \
               python3 -c "import sys, json; print(json.dumps(json.load(sys.stdin), indent=2))" || echo "Failed to decode JWT"
        else
          echo "No OIDC token request token available"
        fi

    # ✅ Use IAM role instead of access keys
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::975050380826:role/GitHubActionsRole
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push backend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd backend
        echo "Building backend with tag: $IMAGE_TAG"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest

    - name: Build and push frontend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd frontend
        echo "Building frontend with tag: $IMAGE_TAG"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest

    - name: Update ECS services
      run: |
        echo "Updating ECS services..."
        aws ecs update-service --cluster medical-ai-cluster --service medical-ai-backend-service --force-new-deployment
        aws ecs update-service --cluster medical-ai-cluster --service medical-ai-frontend-service --force-new-deployment
        echo "Deployment complete!"